#3.2.1
USE PROYECTOINTEGRADOR;
SELECT IDCLIENTE, NOMBRECOMPANIA, CONCAT(DIRECCION, ' - ', CIUDAD, ' - ', PAIS) AS UBICACION FROM CLIENTES_NEPTUNO;
#3.2.2
SELECT IDCLIENTE, NOMBRECOMPANIA, CONCAT_WS(' - ', DIRECCION, CIUDAD, PAIS) AS UBICACION FROM CLIENTES_NEPTUNO;
#3.2.3
SELECT IDCLIENTE, UPPER(NOMBRECOMPANIA) AS EMPRESA, CONCAT_WS(' - ', DIRECCION, CIUDAD, PAIS) AS UBICACION FROM CLIENTES_NEPTUNO;
#3.2.4
SELECT LOWER(IDCLIENTE) AS CODIGO, UPPER(NOMBRECOMPANIA) AS EMPRESA, CONCAT_WS(' - ', DIRECCION, CIUDAD, PAIS) AS UBICACION FROM CLIENTES_NEPTUNO;
#3.2.5
SELECT FECHA, LEFT(SEXO,1) AS SEXO, LEFT (TIPO_PARTO,1) AS TIPO FROM NACIMIENTOS;
#3.2.6
SELECT * , UPPER(CONCAT(LEFT(CIUDAD, 1), LEFT(PAIS,1), RIGHT(PAIS, 2))) AS CODIGO FROM CLIENTES_NEPTUNO;
#3.2.7
DESC NACIMIENTOS;
SELECT SEXO, FECHA, TIPO_PARTO, ATENC_PART, LOCAL_PART, SUBSTRING(FECHA, 4, 2) AS MES
 FROM NACIMIENTOS ORDER BY MES ;
#3.2.8
SELECT SEXO, FECHA, TIPO_PARTO, REPLACE(NACIONALIDAD, 'Chilena', 'Ciudana') AS NACIONALIDAD FROM NACIMIENTOS;
#3.3.1
DESC PEDIDOS_NEPTUNO;
SELECT * FROM PEDIDOS_NEPTUNO WHERE YEAR(FECHAPEDIDO) = 1998;
#3.3.2
SELECT * FROM PEDIDOS_NEPTUNO WHERE MONTH(FECHAPEDIDO) BETWEEN 08 AND 09 AND YEAR(FECHAPEDIDO) = 1997;
#3.3.3
SELECT * FROM PEDIDOS_NEPTUNO WHERE DAY(FECHAPEDIDO) = 01;
#3.3.4
SELECT *, DATEDIFF(CURDATE(), FECHAPEDIDO) AS 'Dias Transcurridos' FROM PEDIDOS_NEPTUNO;
#3.3.5
SELECT *, DATEDIFF(CURDATE(), FECHAPEDIDO) AS 'Dias Transcurridos', DAYNAME(FECHAPEDIDO) AS DIA  FROM PEDIDOS_NEPTUNO;
#3.3.6
SELECT *, DATEDIFF(CURDATE(), FECHAPEDIDO) AS 'Dias Transcurridos', DAYNAME(FECHAPEDIDO) AS DIA,
 DAYOFYEAR(FECHAPEDIDO) AS 'Dia del Año'  
 FROM PEDIDOS_NEPTUNO;
#3.3.7
SELECT *, DATEDIFF(CURDATE(), FECHAPEDIDO) AS 'Dias Transcurridos',
 DAYNAME(FECHAPEDIDO) AS DIA, DAYOFYEAR(FECHAPEDIDO) AS 'Dia del Año',
 MONTHNAME(FECHAPEDIDO) AS MES
 FROM PEDIDOS_NEPTUNO;
#3.3.8
SELECT *, DATEDIFF(CURDATE(), FECHAPEDIDO) AS 'Dias Transcurridos',
DAYNAME(FECHAPEDIDO) AS DIA, DAYOFYEAR(FECHAPEDIDO) AS 'Dia del Año',
MONTHNAME(FECHAPEDIDO) AS MES,
ADDDATE(FECHAPEDIDO, INTERVAL 30 DAY) AS 'Primer Vencimiento'
FROM PEDIDOS_NEPTUNO;
#3.3.9
SELECT *, DATEDIFF(CURDATE(), FECHAPEDIDO) AS 'Dias Transcurridos',
DAYNAME(FECHAPEDIDO) AS DIA, DAYOFYEAR(FECHAPEDIDO) AS 'Dia del Año',
MONTHNAME(FECHAPEDIDO) AS MES,
ADDDATE(FECHAPEDIDO, INTERVAL 30 DAY) AS 'Primer Vencimiento',
ADDDATE(FECHAPEDIDO, INTERVAL 2 MONTH) AS 'Segundo Vencimiento'
FROM PEDIDOS_NEPTUNO;
#3.4.1
SELECT *, ROUND(CARGO * 0.21, 2) AS IVA FROM PEDIDOS_NEPTUNO; 
#3.4.2
SELECT *, ROUND(CARGO * 0.21, 2) AS IVA, ROUND(CARGO * 1.21, 2) AS NETO FROM PEDIDOS_NEPTUNO; 
#3.4.3
SELECT *, ROUND(CARGO * 0.21, 2) AS IVA, ROUND(CARGO * 1.21, 2) AS NETO,
FLOOR(ROUND(CARGO * 1.21, 2)) AS 'Redondeo a favor Cliente'  FROM PEDIDOS_NEPTUNO; 
#3.4.4
SELECT *, ROUND(CARGO * 0.21, 2) AS IVA, ROUND(CARGO * 1.21, 2) AS NETO,
FLOOR(ROUND(CARGO * 1.21, 2)) AS 'Redondeo a favor Cliente',
CEIL(ROUND(CARGO * 1.21, 2)) AS 'Redondeo a favor Empresa' FROM PEDIDOS_NEPTUNO; 
#3.5.1
SELECT COUNT(*) FROM PEDIDOS_NEPTUNO;
#3.5.2
SELECT COUNT(*) AS 'ENTREGAS SPEEDY EXPRESS' FROM PEDIDOS_NEPTUNO  WHERE TRANSPORTISTA LIKE "%SPEEDY EXPRESS%";
#3.5.3
SELECT COUNT(EMPLEADO) AS VENTAS FROM PEDIDOS_NEPTUNO WHERE LEFT(EMPLEADO, 1) = 'C'  ;
#3.5.4
SELECT ROUND(AVG(PRECIOUNIDAD), 2) AS 'PRECIO PROMEDIO' FROM PRODUCTOS_NEPTUNO;
#3.5.5
SELECT ROUND(AVG(PRECIOUNIDAD), 2) AS 'PRECIO PROMEDIO',
MIN(PRECIOUNIDAD) AS 'PRECIO INFERIOR' FROM PRODUCTOS_NEPTUNO;
#3.5.6
SELECT ROUND(AVG(PRECIOUNIDAD), 2) AS 'PRECIO PROMEDIO',
MIN(PRECIOUNIDAD) AS 'PRECIO INFERIOR',
MAX(PRECIOUNIDAD) AS 'PRECIO MAXIMO' FROM PRODUCTOS_NEPTUNO;
#3.5.7
SELECT NOMBRECATEGORIA AS CATEGORIA , MAX(PRECIOUNIDAD) AS 'PRECIO MAXIMO' FROM PRODUCTOS_NEPTUNO  GROUP BY NOMBRECATEGORIA;
#3.5.8
SELECT TRANSPORTISTA, COUNT(IDPEDIDO) AS ENTREGAS FROM PEDIDOS_NEPTUNO GROUP BY TRANSPORTISTA; 
#3.5.9
SELECT SEXO, COUNT(SEXO) AS NACIMIENTOS FROM NACIMIENTOS GROUP BY SEXO;
#3.5.10
SELECT NOMBRECOMPANIA AS CLIENTE, ROUND(SUM(CARGO), 2)  AS 'TOTAL GASTOS'  FROM PEDIDOS_NEPTUNO GROUP BY CLIENTE;
#3.5.11
SELECT SECCION, COUNT(SECCION) AS CANTIDAD FROM PRODUCTOS GROUP BY SECCION ORDER BY CANTIDAD DESC;
#3.5.12
SELECT YEAR(FECHAPEDIDO) AS 'AÑO',MONTH(FECHAPEDIDO) AS MES,COUNT(IDPEDIDO) AS VENTAS FROM PEDIDOS_NEPTUNO
GROUP BY AÑO, MES ORDER BY AÑO, MONTH(IDPEDIDO); 
#3.5.13
SELECT *  FROM  PEDIDOS_NEPTUNO;
SELECT ROUND(SUM(CARGO), 2) AS FACTURACION,
ROUND(AVG(CARGO), 2) AS 'PROMEDIO',
MAX(CARGO) AS 'MEJOR VENTA',
MIN(CARGO) AS 'PEOR VENTA',
COUNT(CARGO) AS VENTAS FROM  PEDIDOS_NEPTUNO
GROUP BY EMPLEADO;