SELECT * FROM clientes_neptuno;
# 2.1.2    
ALTER TABLE  CLIENTES_NEPTUNO MODIFY IDCLIENTE VARCHAR (5) PRIMARY KEY, 
MODIFY NOMBRECOMPANIA VARCHAR(100) NOT NULL,
MODIFY PAIS VARCHAR (15) NOT NULL;

 # 2.1.3
RENAME TABLE CLIENTES TO CONTACTOS;

# 2.1.5)  
ALTER TABLE CLIENTES
MODIFY COD_CLIENTE VARCHAR(7) PRIMARY KEY, 
MODIFY EMPRESA VARCHAR(100) NOT NULL,
MODIFY CIUDAD VARCHAR (25) NOT NULL,
MODIFY TELEFONO  INT UNSIGNED,
MODIFY RESPONSABLE VARCHAR (30);

# 2.1.7)
ALTER TABLE PEDIDOS 
MODIFY NUMERO_PEDIDO INT UNSIGNED PRIMARY KEY,
MODIFY CODIGO_CLIENTE VARCHAR(7) NOT NULL,
MODIFY FECHA_PEDIDO DATE NOT NULL,
MODIFY FORMA_PAGO ENUM('APLAZADO', 'CONTADO', 'TARJETA'),
MODIFY ENVIADO ENUM ('SI', 'NO'); 

# 2.1.9)    
ALTER TABLE PRODUCTOS   
MODIFY COD_PRODUCTO INT UNSIGNED PRIMARY KEY,
MODIFY SECCION VARCHAR(20) NOT NULL,
MODIFY NOMBRE VARCHAR(40) NOT NULL,
MODIFY IMPORTADO ENUM('VERDADERO', 'FALSO'),
MODIFY ORIGEN VARCHAR(25) NOT NULL,
MODIFY DIA INT UNSIGNED NOT NULL,
MODIFY MES INT UNSIGNED NOT NULL,
MODIFY ANO INT UNSIGNED NOT NULL;

#2.3.1) 
SELECT * FROM CLIENTES_NEPTUNO;
#2.3.2 
SELECT NOMBRECOMPANIA, CIUDAD, PAIS FROM CLIENTES_NEPTUNO;
#2.3.3 
SELECT NOMBRECOMPANIA, CIUDAD, PAIS FROM CLIENTES_NEPTUNO ORDER BY PAIS;
#2.3.4
SELECT NOMBRECOMPANIA, CIUDAD, PAIS FROM CLIENTES_NEPTUNO ORDER BY PAIS, CIUDAD;
#2.3.5
SELECT NOMBRECOMPANIA, CIUDAD, PAIS FROM CLIENTES_NEPTUNO ORDER BY PAIS, CIUDAD LIMIT 10;
#2.3.6
SELECT NOMBRECOMPANIA, CIUDAD, PAIS FROM CLIENTES_NEPTUNO ORDER BY PAIS, CIUDAD LIMIT 5 OFFSET 10;
#2.4.1
SELECT * FROM NACIMIENTOS WHERE NACIONALIDAD = 'EXTRANJERA' ;
#2.4.2
SELECT * FROM NACIMIENTOS WHERE EDAD < 18 ORDER BY EDAD_MADRE;
#2.3.3
SELECT  * FROM NACIMIENTOS WHERE EDAD_MADRE = EDAD_PADRE;
#2.3.4
SELECT * FROM NACIMIENTOS WHERE EDAD_PADRE - EDAD_MADRE > 40;
#2.3.5
SELECT * FROM CLIENTES_NEPTUNO WHERE PAIS = 'ARGENTINA';
#2.3.6
SELECT * FROM CLIENTES_NEPTUNO WHERE PAIS <> 'ARGENTINA' ORDER BY PAIS;
#2.3.7
SELECT * FROM NACIMIENTOS WHERE SEMANAS < 20 ORDER BY SEMANAS DESC;
#2.3.8
SELECT * FROM NACIMIENTOS WHERE SEXO = 'FEMENINO'AND NACIONALIDAD = 'EXTRANJERA' AND ESTADO_CIVIL_MADRE = 'SOLTERA'
AND EDAD_MADRE > 40;
#2.3.9
SELECT * FROM CLIENTES_NEPTUNO WHERE PAIS = 'ARGENTINA' OR PAIS = 'BRASIL' OR PAIS = 'VENEZUELA' ORDER BY PAIS, CIUDAD;
#2.3.10
SELECT * FROM NACIMIENTOS WHERE SEMANAS BETWEEN 20 AND 25 ORDER BY SEMANAS;
#2.3.11
SELECT * FROM NACIMIENTOS WHERE  COMUNA IN(1101, 3201, 5605, 8108, 9204, 13120, 15202) ORDER BY COMUNA;
#2.3.12
SELECT * FROM CLIENTES_NEPTUNO WHERE IDCLIENTE LIKE 'C%';
#2.3.13
SELECT * FROM CLIENTES_NEPTUNO WHERE CIUDAD LIKE 'B     ';
#2.3.14
SELECT * FROM NACIMIENTOS WHERE HIJOS_TOTAL > 10;